"""empty message

Revision ID: c77e2d6b2f2f
Revises: 6f7803d7d703
Create Date: 2019-04-05 10:02:06.372469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c77e2d6b2f2f'
down_revision = '6f7803d7d703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stored_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stored_map')
    # ### end Alembic commands ###
